#!/usr/bin/env node
/**
 * Post-content audit. For every post in lib/content/posts.ts, surfaces:
 *   - word count (flag if < 1500)
 *   - hub assignment (so coverage gaps are visible)
 *   - whether the post body references the three differentiator
 *     components (NutritionLedger, CostPerUnitCallout, EvidenceTierBadge
 *     / EvidencePill)
 *   - whether the post cites a USDA FDC URL
 *   - whether the post cites a primary-source URL on PubMed /
 *     ClinicalTrials.gov / NEJM / Examine
 *
 * Pure file reads — no shell, no network. Exit 0 always; survey only.
 */

import fs from "node:fs";
import path from "node:path";
import url from "node:url";

const here = path.dirname(url.fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..");
const postsFile = path.join(repoRoot, "lib", "content", "posts.ts");
const src = fs.readFileSync(postsFile, "utf8");

const SLUG_RE = /\bslug:\s*"([a-z0-9-]+)"/g;
const slugs = [];
let m;
while ((m = SLUG_RE.exec(src)) !== null) {
  slugs.push({ slug: m[1], start: m.index });
}

function sliceForSlug(i) {
  const startIdx = slugs[i].start;
  const endIdx = i + 1 < slugs.length ? slugs[i + 1].start : src.length;
  return src.slice(startIdx, endIdx);
}

function fieldFromSlice(slice, field) {
  const re = new RegExp(`\\b${field}:\\s*"([^"]+)"`);
  const mm = slice.match(re);
  return mm ? mm[1] : null;
}

function bodyWordCount(slice) {
  // Count words inside any string literal in the post slice — covers
  // template literals (body: `…`) and quoted strings (sections: ["…"]).
  const lits = [
    ...[...slice.matchAll(/`([\s\S]*?)`/g)].map((mm) => mm[1]),
    ...[...slice.matchAll(/"((?:\\.|[^"\\])*)"/g)].map((mm) => mm[1]),
  ];
  // Strip URLs + obvious metadata fields so flagged-word output is real prose.
  const prose = lits
    .filter((s) => s.length > 30) // skip slugs / one-line metadata
    .join(" ")
    .replace(/https?:\/\/\S+/g, " ");
  return prose.split(/\s+/).filter(Boolean).length;
}

function hasMarker(slice, marker) {
  return slice.toLowerCase().includes(marker.toLowerCase());
}

const HUBS = [
  "macros-protein",
  "pantry-systems",
  "ingredient-deep-dives",
  "meal-prep",
  "supplements-functional-foods",
];
const HUBSET = new Set(HUBS);

const rows = [];
const hubCounts = Object.fromEntries(HUBS.map((h) => [h, 0]));

for (let i = 0; i < slugs.length; i++) {
  const slice = sliceForSlug(i);
  const slug = slugs[i].slug;
  const hub = fieldFromSlice(slice, "hub");
  const postType = fieldFromSlice(slice, "postType");
  if (!hub || !HUBSET.has(hub)) continue;

  const wc = bodyWordCount(slice);
  const usdaCited =
    /fdc\.nal\.usda\.gov/.test(slice) || /\busdaSlug:\s*"/.test(slice);
  const pubmedCited =
    /pubmed\.ncbi\.nlm\.nih\.gov|clinicaltrials\.gov|nejm\.org|examine\.com/.test(slice);
  // Differentiator wiring is detected via either:
  //   - explicit component name in the post body / template, OR
  //   - opt-in field flag on the Post record (usdaSlug, costPerUnit,
  //     evidenceTierSlug) which the article templates pick up
  //     conditionally.
  const hasLedger =
    hasMarker(slice, "NutritionLedger") || /\busdaSlug:\s*"/.test(slice);
  const hasCost =
    hasMarker(slice, "CostPerUnitCallout") || /\bcostPerUnit:\s*\{/.test(slice);
  const hasEvidence =
    hasMarker(slice, "EvidenceTierBadge") ||
    hasMarker(slice, "EvidencePill") ||
    /\bevidenceTierSlug:\s*"/.test(slice);

  hubCounts[hub] += 1;

  const flags = [];
  if (wc < 1500) flags.push(`words=${wc}<1500`);
  if ((hub === "ingredient-deep-dives" || hub === "meal-prep") && !usdaCited)
    flags.push("missing-usda");
  if (hub === "supplements-functional-foods" && !hasEvidence)
    flags.push("missing-evidence-pill");
  if (hub === "pantry-systems" && !hasCost) flags.push("missing-cost-callout");
  if (!pubmedCited && hub !== "pantry-systems") flags.push("no-primary-source");

  rows.push({
    slug,
    hub,
    postType,
    wc,
    usdaCited,
    pubmedCited,
    hasLedger,
    hasCost,
    hasEvidence,
    flags,
  });
}

const today = new Date().toISOString().slice(0, 10);
const outDir = path.join(repoRoot, "docs", "research");
fs.mkdirSync(outDir, { recursive: true });
const outPath = path.join(outDir, `post-audit-${today}.md`);

let md = `# Larderlab post audit — ${today}\n\n`;
md += `Auto-generated by \`pnpm audit:posts\`. ${rows.length} editorial posts surveyed.\n\n`;
md += `## Hub coverage\n\n| Hub | Posts |\n|---|---|\n`;
for (const h of HUBS) md += `| ${h} | ${hubCounts[h]} |\n`;
md += `\n## Per-post flags\n\n`;
md += `| Slug | Hub | Type | Words | USDA | RCT cite | Ledger | Cost | Evidence | Flags |\n`;
md += `|---|---|---|---:|:-:|:-:|:-:|:-:|:-:|---|\n`;
for (const r of rows) {
  md += `| \`${r.slug}\` | ${r.hub} | ${r.postType} | ${r.wc} | ${r.usdaCited ? "Y" : "-"} | ${r.pubmedCited ? "Y" : "-"} | ${r.hasLedger ? "Y" : "-"} | ${r.hasCost ? "Y" : "-"} | ${r.hasEvidence ? "Y" : "-"} | ${r.flags.join(" / ") || "ok"} |\n`;
}
md += `\n## Hub-coverage gaps (vs. spec target >= 12 per hub)\n\n`;
for (const h of HUBS) {
  const need = Math.max(0, 12 - hubCounts[h]);
  md += `- **${h}**: ${hubCounts[h]} live, ${need} more needed.\n`;
}

fs.writeFileSync(outPath, md, "utf8");

console.log(`Larderlab post audit: ${rows.length} posts surveyed.`);
console.log(`Report: ${path.relative(repoRoot, outPath)}`);
console.log("");
console.log("Hub coverage:");
for (const h of HUBS) console.log(`  ${h.padEnd(32)} ${hubCounts[h]}`);
const flagged = rows.filter((r) => r.flags.length > 0);
console.log("");
console.log(`Flagged posts: ${flagged.length} / ${rows.length}`);
for (const r of flagged.slice(0, 20))
  console.log(`  ${r.slug.padEnd(44)} ${r.flags.join(" / ")}`);
if (flagged.length > 20) console.log(`  ... +${flagged.length - 20} more`);
